### ISSUE TITLE
Did I miss some requirements to get it to work ?

### ISSUE THREAD

**Issue by k4nfr3** [powerseb/PowerExtract#4]
Tried on a Win10-22H2 and on a Win10-1909 but same result.

PS C:\temp\PowerExtract> Invoke-PowerExtract -PathToDMP C:\temp\lsass.DMP
New-Object : Cannot find type [â€TypeName System.IO.FileStream â€ArgumentList]: verify that the assembly containing
this type is loaded.
At C:\temp\PowerExtract\Invoke-PowerExtract.ps1:409 char:23
+ ... ileStream = New-Object â€“TypeName System.IO.FileStream â€“ArgumentLi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : Cannot find type [â€TypeName System.IO.BinaryReader â€ArgumentList]: verify that the assembly containing
this type is loaded.
At C:\temp\PowerExtract\Invoke-PowerExtract.ps1:410 char:23
+ ... ileReader = New-Object â€“TypeName System.IO.BinaryReader â€“Argument ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

The property 'Position' cannot be found on this object. Verify that the property exists and can be set.
At C:\temp\PowerExtract\Invoke-PowerExtract.ps1:412 char:9
+         $fileReader.BaseStream.Position=0
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At C:\temp\PowerExtract\Invoke-PowerExtract.ps1:413 char:9
+         $Signature = Convert-LitEdian -String ([System.BitConverter]: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\PowerExtract\Invoke-PowerExtract.ps1:415 char:9
+         $Version = Convert-LitEdian -String ([System.BitConverter]::T ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\PowerExtract\Invoke-PowerExtract.ps1:417 char:9
+         $ImplementationVersion = Convert-LitEdian -String ([System.Bi ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by powerseb** [comment]
Hmm usally it does not have any requirement (given that you have an unrestricted PowerShell - in regards to execution policy and language mode). The error looks like a encoding issue so ensure that the script is transferred as UTF-8 (e.g. when you transfer it by invoke-webrequest).

**Comment by k4nfr3** [comment]
a did a git clone, but indeed there is something funny with the encoding.
A good old copy paste from raw file solved the issue.
